### ISSUE TITLE
Not working with GTA V Online

### ISSUE THREAD

**Issue by Adenis890** [juv/vibranceGUI#100]
Hi there,

I tried searching and found nothing so i decided to ask here, for some reason vibranceGUI works fine on GTA V Story Mode but when i load up Online i have no vibrance. I tried different exes from the folder and nothing. The current exe i'm using is GTAV.exe, am i doing something wrong or is there another exe that i just can't find.
(also i can't select the desktop icon since it's going to give me a error, i have to directly put in the exe of the game/app)

**Comment by juv** [comment]
Have you checked if you use the correct .exe file in the task manager? You can right click the process and select "show file path" and it should navigate your Windows explorer to the correct file

**Comment by Adenis890** [comment]
> Have you checked if you use the correct .exe file in the task manager? You can right click the process and select "show file path" and it should navigate your Windows explorer to the correct file

Yeah it navigates to GTAV.exe. I guess they just not allow it.

**Comment by juv** [comment]
Have you tried adding it from the built-in process browser when you are in-game in GTA V Online?

**Comment by Adenis890** [comment]
> Have you tried adding it from the built-in process browser when you are in-game in GTA V Online?

i tried adding the process while in gta online and while alt-tabbing it worked once and after i alt-tabbed again it didn't work anymore

**Comment by juv** [comment]
> > Have you tried adding it from the built-in process browser when you are in-game in GTA V Online?
> 
> i tried adding the process while in gta online and while alt-tabbing it worked once and after i alt-tabbed again it didn't work anymore

Can you try this pre-release build with a fix for alt-tab issues that occur infrequently?
https://github.com/juv/vibranceGUI/issues/95#issuecomment-750918557

**Comment by Adenis890** [comment]
> > > Have you tried adding it from the built-in process browser when you are in-game in GTA V Online?
> > 
> > 
> > i tried adding the process while in gta online and while alt-tabbing it worked once and after i alt-tabbed again it didn't work anymore
> 
> Can you try this pre-release build with a fix for alt-tab issues that occur infrequently?
> [#95 (comment)](https://github.com/juv/vibranceGUI/issues/95#issuecomment-750918557)

I'm very sorry for the late reply.
I tried the pre-release build and it works perfectly. The vibrance is staying on even if i alt tab. Thank you a lot!

**Comment by juv** [comment]
Glad to hear that. I'm closing this issue then.
