### ISSUE TITLE
Dual GPU driver issue

### ISSUE THREAD

**Issue by PrayHE** [juv/vibranceGUI#101]
Alltogether I really love this tool and I will also donate something because I've been using this utility for such a long time and I just can't live without it. Thank you for this awesome piece of software!
One problem I have is the following:
I have installed macOS besides Windows on my PC. The macOS only supports AMD GPUs.
I also have another GPU from NVIDIA which I'm using in Windows because its a more powerful one.
I simply disabled the AMD GPU in my Device-Manager and never had any issues with it.
Only VibranceGUI refuses to load because it thinks I didn't properly delete my AMD-Drivers (which I never had in the first place).
To fix it I had to go into my windows folder and delete atiadlxx.dll and/or atiadlxy.dll
I don't know if those two files actuallly interfere with VibranceGUI or if they are only used to "detect" the AMD-Drivers.
I know I'm probably the only one in this exact use-case, but still I just wanted to let you know this.

**Comment by juv** [comment]
Hi @PrayHE, you are correct that vibranceGUI detects those files to determine if the AMD gpu drivers have been installed correctly. "Installed correctly" as in vibranceGUI can communicate with the AMD gpu by utilizing the AMD driver libraries. So there had been issues where people had multiple GPU drivers installed and this causes the application to be unable to function properly. 

I wonder why you have those files when you say that you did not even install an AMD driver? Most likely Windows installed the driver when you launched Windows without having the NVIDIA card plugged in. 

You could try the "display driver uninstaller" tool to entirely remove AMD drivers from your system

**Comment by PrayHE** [comment]
It seems like these files are automatically created again once the GPU is enabled in the device-manager.
But since I keep it disabled anyway it's not that big of a deal to delete these files once.
I just didn't know if this is an intended behaviour or not. Thank you for responding!
