### ISSUE TITLE
Both NVIDIA AND AMD FOUND ON YOUR SYSTEM - but i'm mining coin with my 2nd gpu :(

### ISSUE THREAD

**Issue by tastyhub** [juv/vibranceGUI#102]
Any chance to offer an option to disable this notification? Its nice that you are trying to help the end user, but it disables vibrancegui all together.

Thanks!
![Screenshot 2021-03-23 145054](https://user-images.githubusercontent.com/136613/112209200-35211980-8be7-11eb-80ac-2b21b09c38bc.png)

**Comment by bigfinfrank** [comment]
This should probably be a "Do you really know what you're doing?" popup with an option to pick which driver type you want VibranceGUI to use.

**Comment by hfghwpgg** [comment]
before posting your own, check for resolved issues reported by other users. 
https://github.com/juv/vibranceGUI/issues/67

**Comment by Sxlarzz** [comment]
download the amd or nvdia one
[vibranceGUI_amd_only.zip](https://github.com/juv/vibranceGUI/files/2734136/vibranceGUI_amd_only.zip)
[vibranceGUI_nvidia_only.zip](https://github.com/juv/vibranceGUI/files/2734133/vibranceGUI_nvidia_only.zip)

**Comment by skyrage45** [comment]
> download the amd or nvdia one [vibranceGUI_amd_only.zip](https://github.com/juv/vibranceGUI/files/2734136/vibranceGUI_amd_only.zip) [vibranceGUI_nvidia_only.zip](https://github.com/juv/vibranceGUI/files/2734133/vibranceGUI_nvidia_only.zip)

GOATTT THANK YOU MAN
