### ISSUE TITLE
How do I set it back to normal and uninstall it?

### ISSUE THREAD

**Issue by ojm50** [juv/vibranceGUI#104]
How do I set VibranceGUI back to normal (like normal vibrance, before I opened VibranceGUI), and then how do I uninstall?

**Comment by juv** [comment]
Add one application to the program list, set windows vibrance level to 50%
(nv) or 100 (amd), then tab into some program and the vibrance should be
back to normal.

For uninstalling, disable autostart, close/quit vibrancegui and delete the
exe

ojm50 ***@***.***> schrieb am Fr. 11. Juni 2021 um 00:39:
