### ISSUE TITLE
Cannot reset vibrance

### ISSUE THREAD

**Issue by semendanshin** [juv/vibranceGUI#109]
Hello. I successfully used vibrancegui for a while, but then I noticed that the increased saturation became constant. I tried changing the program settings, deleting it, reinstalling the nvidia driver, but nothing helps. In the nvidia control panel, the digital intensity is at 50, but the picture is still oversaturated.

**Comment by juv** [comment]
When your digital vibrance value is at 50% inside of Nvidia control panel, then something in your GPU drivers bugged out. I suggest reinstalling your GPU driver. This usually helps.

**Comment by semendanshin** [comment]
DDU didn`t help(
