### ISSUE TITLE
Virustotal flag

### ISSUE THREAD

**Issue by Nirgranth** [juv/vibranceGUI#112]
https://www.virustotal.com/gui/file/1cbaa4d4c817743a7ec88bdc3f8d15200e543a86e0b3374c6d05a15a0762970f/community

anyone know why its flagged and any more info will be appreciated

**Comment by juv** [comment]
This topic was brought up in a Reddit thread yesterday. You can find a little bit more detailed review of the warnings in the automated malware analysis from virustotal/hybrid-analysis here:
https://www.reddit.com/r/GlobalOffensive/comments/rsovm1/comment/hqo5s2e
https://www.reddit.com/r/GlobalOffensive/comments/rsovm1/comment/hqowyuf

Make sure to always download binaries from the official website

**Comment by Nirgranth** [comment]
Find more info here 
https://www.reddit.com/r/GlobalOffensive/comments/rsovm1/vibrance_gui_suspicious_behaviour/

TL:DR; Its okay
