### ISSUE TITLE
VibranceGUI error drivers

### ISSUE THREAD

**Issue by Laudster00** [juv/vibranceGUI#117]
Hello guys, I have already removed all the old drivers that I forgot to remove from my previous video card, but the application still insists that they are still here, does anyone know how to solve?

**Comment by juv** [comment]
Hi, did you try uninstalling the old drivers with the "display driver uninstaller" tool? That tool will clean up all leftovers. 

Vibrancegui is basically performing the driver check by searching for certain driver files on your pc. There should be no false positives in this detection.

**Comment by Laudster00** [comment]
yes, I downloaded the "Display Driver uninstaller" and did all the paços but the warning continues to appear

**Comment by juv** [comment]
If your old gpu is from AMD: delete/rename/move files "atiadlxy.dll" and/or "atiadlxx.dll" out of your Windows folder
If your old gpu is from NVIDIA: delete/rename/move file "nvapi.dll" out of your Windows folder

**Comment by niktok123** [comment]
my ddu aint working any help with that

**Comment by juv** [comment]
> my ddu aint working any help with that

Please see the comment above. There must be leftover files even if DDU tells you it has cleaned up everything. You can manually remove the leftovers for driver that you are not using anymore. See the file names above. 

I am closing this issue
