### ISSUE TITLE
PLEASE SOMEONE HELP

### ISSUE THREAD

**Issue by gosnje** [juv/vibranceGUI#118]
I adjust it to max and it closed and my csgo is now all green and i cant play it and if i want to go back in vibrancegui it says that can only be opened one time and i dont no how to fix it please someone help me i tried unistalling and installing the game but it didnt work!!!!

**Comment by juv** [comment]
Check your Windows tray menu, you probably just minimized the application and it is still running? If not, you can stop the process in task manager and restart the application
