### ISSUE TITLE
Vibrancegui AutoStartup error

### ISSUE THREAD

**Issue by miltoz** [juv/vibranceGUI#119]
so, i just reinstalled windows 10 on my pc and when i went to turn on autostart on vibrancegui i got this scary popup, after that i wiped my drivers with ddu and reinstalled everything but it keeps coming back every time i activate autostartup and it wont start autommatically, please help me fix this issue.
![Screenshot 2022-05-25 010103](https://user-images.githubusercontent.com/89163879/170177399-4b46519b-36ce-4f36-a451-1f6af463bdcc.png)
![Screenshot 2022-05-25 010122](https://user-images.githubusercontent.com/89163879/170177406-2405cca7-cec3-4900-81c8-af21d89f2761.png)

**Comment by juv** [comment]
Hi, this exception mesaage can not break anything on your pc, so you have nothing to worry about except that vibrancegui can not be regiatered to autostart. Can you copy the exception text and paste it here? Thanks

**Comment by juv** [comment]
Have you tried to start vibranceGUI as an administrator?
Can you try to manually add vibranceGUI to your autostart in the task manager? [Here ](https://support.microsoft.com/en-us/windows/add-an-app-to-run-automatically-at-startup-in-windows-10-150da165-dcd9-7230-517b-cf3c295d89dd) is a guide from microsoft.

**Comment by miltoz** [comment]
Yes, i know i can put it in shell:startup, but it opens the window when it starts up so i really want to fix this so it can startup normally. I tried running it with administrator but nothing changed so i dont know what to do, thanks for your help though, i really appreaciate it. :) btw i also tried the first version and its the same there aswell.

**Comment by miltoz** [comment]
couldnt fix the error so i just gave up and used this method: https://superuser.com/questions/1223465/how-to-start-any-file-on-startup-hidden , i found out that the error probably has something to do with my pirated version of visual studio 2022 so its completely my fault to begin with :D

**Comment by juv** [comment]
to start the application in minimized window mode, you can just create a link of the vibranceGUI.exe file, go to the link properties, then append a ` -minimized` to the **destination** of the link. then put that into your autostart. it's virtually the same thing that the application is doing in code: https://github.com/juv/vibranceGUI/blob/master/vibrance.GUI/common/VibranceGUI.cs#L263

**Comment by miltoz** [comment]
thaks! i already did it!
