### ISSUE TITLE
Alt+tabbing from or to CSGO takes 5 seconds when VibranceGUI is open.

### ISSUE THREAD

**Issue by zisis912** [juv/vibranceGUI#121]
For context, csgo normally instantly alt tabs like every other application. But when I add it on vibrancegui so as to change its digital vibrance, I noticed that the alt tab time massively increased. I dont even need to turn off vinbrance gui, just removing csgo from it is enough to make it go back to normal. That's why I'm certain it has to do with the program. Any fixes?

**Comment by juv** [comment]
Hi, what GPU do you have?

**Comment by juv** [comment]
Closing as no feedback was given
