### ISSUE TITLE
I want to set it below 50%

### ISSUE THREAD

**Issue by G1ll0u** [juv/vibranceGUI#139]
Everything is in the title, I want to be able to set vibrance to less than 50% for specific exes.

Because my eyes hate colors and I'm tired of always going to shitty NVidia Control Panel.

Btw, thanks for this piece of software !
And have a nice day.

**Comment by powerswing** [comment]
yeah same plz implement, it's a one line change would've done it myself but don't want to recompile plz thanks!

**Comment by juv** [comment]
Hi, this is a duplicate of https://github.com/juv/vibranceGUI/issues/62
