### ISSUE TITLE
Vibrance on laptops is possible

### ISSUE THREAD

**Issue by JoiNNN** [juv/vibranceGUI#19]
I wanted to try the app and noticed that there is no laptop support the reason being that nVIDIA didn't include support for vibrance. However this is not entirely true. On modern laptops at least, you have control for  **Vibrance** via the Intel's Graphics Control Panel, is named **Saturation**. 
![gfxv4_0_2016-03-27_22-04-03](https://cloud.githubusercontent.com/assets/3322834/14067710/34f87034-f46b-11e5-83cd-c75e403a86cf.png)
This is because the integrated GPU is the one handling the image output to the display and not the nVIDIA GPU. The dedicated GPU is like an addon in this case, that does the heavy lifting when necessary then passes information to the integrated GPU which then outputs it to the screen.
What I'm trying to say is that there is the possibility of adding support for laptops given you have the resources to do so in terms of Intel API documentation on this matter, in which I haven't looked at all so I wont be able to provide more information.

Anyway thanks for the app, will definitely use it on my desktop PC.

**Comment by juvlarN** [comment]
Hi,

as there were many requests to adding Intel support to vibranceGUI, I've researched whether there is an API that allows to retrieve and change the color settings of a specific display. Apparently there is no public API at all. Furthermore I do not have access to a laptop where I could test the Intel support. Trying to get it running without access to a laptop that is able to run the program is like finding a needle in a haystack. If there was such an API, someone else would have to program the Intel support, like @juRiii did for AMD graphic cards.

**Comment by aPollO2k** [comment]
Also if external display is in use and the HDMI/DisplayPort is directly connected to the nvidia gpu there IS a option for digital vibrance in the nvidia driver. vibranceGUI works well with external display BUT if i add it to the system startup i get every time an error while no external display is connected. Maybe you can make a little feature.
I think its very useful if vibranceGUI can check if there is an external display/digital vibrance option and then start or just idle if there is not.

Sorry my english is not very well. I hope everyone understands.

**Comment by luisrudge** [comment]
I don't have these options in my control panel :(

![image](https://cloud.githubusercontent.com/assets/941075/18532457/96c96ac0-7ab2-11e6-8852-e510c56a40a6.png)

![image](https://cloud.githubusercontent.com/assets/941075/18532478/b5fe3d4e-7ab2-11e6-9679-0e43c405e1c6.png)

http://www.lg.com/us/monitors/lg-29UM67-P-ultrawide-led-monitor

Any thoughts?

**Comment by daniele-salvagni** [comment]
It is indeed possible, the problem as @juvlarN said is that there isn't a public API. I managed to reverse engineer the Intel HD Graphics Control Panel, it is using a proprietary library called `igfxDHLib.dll` which is obviously not documented. I managed to reverse that too (I'm still not sure about some parts of the library) and to put together some code about 5 months ago that has been working perfectly for me ever since.

It wasn't intended for public release (bad code warning) and I didn't had the time to keep working on it. I also suspect that it won't immediately work for any system as some stuff might vary based on the GPU/Driver version. If you want to try it out this is the repository: https://github.com/daniele-salvagni/color-goggles

My laptop is a dual-graphichs Sony Vaio S13P with an Intel® Core™ i7-3520M (HD Graphics 4000), it may not work for different systems (I didn't had any other system to compare/test).

Anyways on some version of the Intel Control Panel it is possible to setup profiles to switch profiles automatically when you open certain applications, is is a bit wonky but it might be worth looking into.

**Comment by zerox06** [comment]
Hello Daniele, I interested to try your stuff, im new on github, I thought that I could find a .exe to start the software but there isn't :/

I got a 960m and i7 6700hq 

Thank you for answer

**Comment by daniele-salvagni** [comment]
Hi @zerox06, you can find a download link for the executable here: https://daniele-salvagni.github.io/color-goggles/, there is a `Test` button in the application which should increase your saturation to minimum, maximum and back to normal if it is working. It may just crash as I was able to test this only on my system, it is just a fast "prototype" so I didn't take the time to manage exceptions. Let me know how it goes via email (you can find it in my GitHub profile) so we don't pollute too much this discussion which should be used just for `VibranceGUI`.

**Comment by Dreamer707** [comment]
Hello JoiNNN I have a intel i5 and I dont have these settings... why?

**Comment by avaque** [comment]
@daniele-salvagni the thing is that your program simply alters what we can already do ourselves in intel control panel (as displayed in the pic on top of the post)
im looking to go further if its possible, cause vibrancegui pushes it so much further, but then again it may not be possible simply cause of intels dumbass limits

**Comment by daniele-salvagni** [comment]
@avaque VibranceGUI does the same but with Nvidia Settings, staying within the limits dictated by Nvidia. It is not possible to further increase the vibrance via software while still being VAC safe, I might check if the Intel limit can be bypassed on the driver level but I won't get my hopes up about that.

**Comment by daniele-salvagni** [comment]
It is kinda possible to bypass the limit, however we fall in the undefined behaviour realm (this should also be device-dependent). This is what happens at different saturation levels:

- 0%: Normal level
- 100%: Intel limit
- 330%: Sweet spot behind the limits

From here the saturation starts to affect the hue effectively decreasing the visibility:

- 470%: Green hue takes over
- 950%: Red hue takes over

![sat](https://user-images.githubusercontent.com/6751621/34653901-ab39b99a-f3f3-11e7-9bca-7e85e929f995.jpg)

I will investigate this further and push a new version to take advantage of this, however it might take a while as I will be quite busy for the next month or so.

**Comment by zerox06** [comment]
Go further Intel limite would be awesome thèse colors are so nice

Le 7 janv. 2018 21:48, "Daniele Salvagni" <notifications@github.com> a
écrit :

**Comment by avaque** [comment]
@daniele-salvagni the 330% is just what im looking for. Ive searched alot and found nothing which could lead to further saturation increase than what i have right now. Only closest thing ive found is Color filter option in Windows 10 where the "Deuteranopia" option increases saturation but only of green and red colors.

**Comment by daniele-salvagni** [comment]
**Color-Goggles v1.0.0** is out: http://dan.salvagni.io/s/color-goggles/

![CG](https://user-images.githubusercontent.com/6751621/34745778-e9e03b98-f591-11e7-98e8-0c47e67e45f6.png)

It is a complete rewrite of the applciation and it is now possible to increase the saturation up to **320%** (check the `Remove limits` option). I just sold my old laptop, so I wasn't able to test it on more than one device, please let me know how it goes.  You can contact me directly at [@sdlnv](https://twitter.com/sdlnv) on twitter or dan@salvagni.io.

**Comment by avaque** [comment]
@daniele-salvagni thank you sooo much. I just dont understand why didnt intel do it in the first place.

**Comment by NeedHelperino** [comment]
@daniele-salvagni i need to find a file name igfxDHLib.dll but i dont have that file in my filerepository

**Comment by avaque** [comment]
@needhelperino its in one of the folders definitelly, have you tried searching "igfxdhlib"in the search tab?
and pick the newest one by date

**Comment by daniele-salvagni** [comment]
@NeedHelperino I need some more details in order to be able to help you. Are you on a Desktop/Laptop? What's your CPU? Do you have a dedicated GPU? Which one?

**Comment by NeedHelperino** [comment]
Yes i have an Laptop i have an I3-3217U CPU and an dual GPU 1st GPU intel hd graphics and my 2nd GPU is an 770M Nivida

**Comment by NeedHelperino** [comment]
@avaque yes i did find it but i dont know where to put the file

**Comment by avaque** [comment]
@needhelperino in the same folder with the colorgoggles.exe and its .dll

**Comment by NeedHelperino** [comment]
@avaque look this might seem pretty stupid but when i extract the file i dont know where to put it i cant find it in my roaming i cant find it in my download page i dont know where to look

**Comment by daniele-salvagni** [comment]
You can extract `color-goggles.exe` wherever you want, even in a folder on the Desktop. You then need to copy `IgfxDHLib.dll` you found in the same folder as `color-goggles.exe`.

**Comment by NeedHelperino** [comment]
i made a new map put it on my desktop than got the extracted files put them in the map and copied the IgfxDHLib.dll in to the map what now

**Comment by avaque** [comment]
if by "map" you mean "folder" then just launch the .exe

**Comment by freaky1337** [comment]
@daniele-salvagni Is this program VAC safe?

**Comment by avaque** [comment]
@freaky1337 Unlike SweetFX this program doesnt change 3d vibrance but rather overall vibrance. Its just like applying a filter over your screen. Its completely VAC safe. Nvidia Freestyle has this same option but it will probably get disabled for CSGO soon and it lowers your FPS anyways, while Colorgoggles doesnt.

**Comment by freaky1337** [comment]
The program doesnt't do anything,and my anti-virus detected it.

**Comment by avaque** [comment]
@freaky1337 so does everyone's antivirus. Have you followed the instructions to install it?

**Comment by freaky1337** [comment]
I did

**Comment by freaky1337** [comment]
My AV didn't detect VibranceGUI

**Comment by avaque** [comment]
@freak1337 then use vibranceGUI man idk what to tell you if you worried about getting a virus from this just dont use it.

**Comment by freaky1337** [comment]
can't,cuz i have laptop

**Comment by daniele-salvagni** [comment]
@freaky1337 Which antivirus are you using? I can't get a positive result on [any of them](https://www.virustotal.com/#/file/73c6109c754ae35fa9b49d382e7db477a44806b85952476a720e36151ebafa43/detection).
Anyway you should be able to add the file as an exception in your AV settings.

**Comment by brandons101** [comment]
I'm on my desktop and I don't have a igfxDHLib.dll what should I do?

**Comment by Dreamer707** [comment]
Oh sounds serious, what is that?

Am Mo., 24. Dez. 2018 02:46 hat brandons101 <notifications@github.com>
geschrieben:

**Comment by daniele-salvagni** [comment]
Sorry for the delay @brandons101, if you are using the new DCH drivers, you should try following these instructions: https://github.com/daniele-salvagni/color-goggles/issues/16#issuecomment-513561967

**Comment by meta-Lord** [comment]
While looking online I found several articles saying that digital vibrance and saturation are different things. It said that digital vibrance will not saturate darker colors and will only saturate lighter colors, while the saturation option will saturate all colors making dark colors extremely dark. If this is true is there any way to get around the saturation bumping up dark colors.

**Comment by njanadesign** [comment]
when I use Color-Goggles, my FPS drops on csgo :(

**Comment by daniele-salvagni** [comment]
> when I use Color-Goggles, my FPS drops on csgo :(

This is not possible, you can even close Color-Goggles after changing the saturation because it will not be doing anything at all. If your FPS are dropping there is another reason.

**Comment by Kretisy** [comment]
Im on a desktop with intel UHD 630 graphics and i cant find igfxDHLib.dll what should i do?

**Comment by Younase** [comment]
vibranceGUI didn't work for me (since nvidia laptops are not supported) so i made this script, hope it helps someone.
https://gist.github.com/Younase/5cc1114812e7839585c06964086e3c1b
