### ISSUE TITLE
VibranceGUI Alt Tab issue

### ISSUE THREAD

**Issue by sprylog** [juv/vibranceGUI#52]
Having trouble while alt tabbing in cs go and payday 2,  some times it csgo when i alt tab, and payday 2 when i alt tab it goes back to the game, and i have to alt tab a couple of times to go to my desktop

**Comment by juvlarN** [comment]
How do you think this is related to vibranceGUI?

**Comment by sprylog** [comment]
because it only happens with vibranceGUI opened, when i close it it fixes this issue

**Comment by jeffreylec** [comment]
When I alt tab, vibrance gets messed up and doubles the vibrance and messes up my resolution.

**Comment by juvlarN** [comment]
Give me a detailed step-by-step explanation of how to reproduce this issue please.
I am not facing the error you see. And which vibranceGUI are you using? Also mention some information about your gpu as well as Windows version.

**Comment by eritongomez** [comment]
I have the same issue:
when I am playing Battlefield 1 and I press alt tab to do something out of the game and return to the game, the colors return to normal as if the vibrancegui was not running. The vibrancegui settings only reappear after restarting the pc:
Windows 10 build 1803
gtx 1070 driver 397.31

**Comment by juvlarN** [comment]
@eritongomez How do you return back to the game? Sometimes Windows does not fire the "Application-Context-Has-Changed"-Event when pressing on the icon in the Windows task bar. Try to Alt+Tab back into the game instead of clicking on the icon in your task bar and see if that helps. Does this only happen in fullscreen or also when you are in Windowed Fullscreen mode?

**Comment by eritongomez** [comment]
@juvlarN Whatever. If i return with click or alt tab, the problem happens in two ways. And it also happens with full screen or windowed.
my "solution" at the moment is to ignore everything out of the game... :(

**Comment by juvlarN** [comment]
@eritongomez it does work in other games though? I am not sure if this is actually a problem of vibranceGUI rather than a problem of BF1?
