### ISSUE TITLE
VibranceGUI Always on?

### ISSUE THREAD

**Issue by Joe-Alderdice** [juv/vibranceGUI#58]
I'm not sure what I did, but I put the vibrance for CS:GO from 70% to 100% and now, my very left-hand monitor (1/3) is always at 100% vibrance and It's really annoying, I've even tried removing the program and it remained like that.

**Comment by juvlarN** [comment]
You can always manually reset the vibrance level for any monitor in your NVIDIA control panel. Go to Display -> Desktop Color settings and switch back the vibrance level to whatever you prefer.

When you face this error again, please let me know about the steps to reproduce this issue. Thanks

**Comment by juvlarN** [comment]
Any info on how to reproduce?

**Comment by juvlarN** [comment]
> same problem. Desktop Color settings in NVDIA already set to default and still my monitor vibrance is way up.

this does not happen when vibrancegui is closed?

**Comment by divmonkey** [comment]
Followed these steps, didn't help. But I resolved it by reinstalling NVIDIA driver.

**Comment by juv** [comment]
Closing this as no info on how to reproduce is given. If it happens again, open this issue again and tell me how to reproduce if possible please. Also remember to update to the latest version before trying.
