### ISSUE TITLE
VibranceGui changing what ?

### ISSUE THREAD

**Issue by alohottin** [juv/vibranceGUI#63]
Helle Developer ;
I need some information and help 
I wondering how the VibranceGui work, I know it is changing saturation but how ? (regedit or something ?)
I'm wondering because I set some digital vibrance for H1Z1 and I deleted this but it still using old settings. And I can't delete this because I can't see settings in VibranceGui ui. 
How can I fix this ?

Here is screenshot 
[https://prnt.sc/iuf7u9](url)

**Comment by juvlarN** [comment]
Have you tried to re-add H1Z1 and set the ingame value to 50% (which is the default value)?

**Comment by alohottin** [comment]
Yes, I tried but no result. But when I close VibranceGui it will be turning default digital vibrance.

**Comment by juvlarN** [comment]
Go into folder %appdata%\vibranceGUI\ (start Explorer -> type %appdata%\vibranceGUI\ ) then open applicationData.xml and search for h1z1 and see if it is still in there for some reason. If it is, remove  the entire XML element surrounding the h1z1 exe path, this means the entire <ApplicationSetting></ApplicationSetting> block.

**Comment by alohottin** [comment]
Thanks for the help. It works. But why I can't see in VibranceGui ui. It is bug or my mistake ?

**Comment by juvlarN** [comment]
It is a bug, I will look into this. It probably has something to do with the configuration data not being saved in a proper way.

**Comment by juv** [comment]
This should be fixed
