### ISSUE TITLE
vibranceGUI not opening

### ISSUE THREAD

**Issue by JesWhite** [juv/vibranceGUI#72]
i'm using windows 10 my laptop.
i know my laptop not supporting vibranceGUI...
but i want to only one function your app..
i  want screen resolution ingame...
if i want to join game my screen resolution to be 1024x768
if i want to quit from game my resolution is back to 1920x1080.
how can i do this?
and i saw your app is doing this but not opening.
if you are fix it i can do this.
thanks.

**Comment by juvlarN** [comment]
There might be other tools like "hotkey resolution changer". If you google for that, you will find a few options you can choose from. Good luck
