### ISSUE TITLE
Sometimes after Windows restart, value of saturation in AMD driver is set to 0

### ISSUE THREAD

**Issue by partoftheworlD** [juv/vibranceGUI#74]
Sometimes after Windows restart, value of saturation in AMD driver is set to 0 and screen becomes black and white.

**Comment by juv** [comment]
@partoftheworlD when this happens again, can you please go into the folder %appdata%\vibranceGUI and upload vibranceGUI.ini and applicationData.xml here?

**Comment by partoftheworlD** [comment]
Sure

**Comment by partoftheworlD** [comment]
Started using vibranceGUI again and this time managed to reproduce the bug. If log out of user account several times, saturation is reset to 0 and can only be restored by manually changing the value.

[reproducing bug](https://youtu.be/C6P61m6l41U)

[vibranceGUI.zip](https://github.com/juv/vibranceGUI/files/7246274/vibranceGUI.zip)
