### ISSUE TITLE
Screen Resolution Not Changing Back to Default After Closing Game

### ISSUE THREAD

**Issue by caspertheghost1337** [juv/vibranceGUI#77]
Hey. I love your program and I use it all the time, but recently I have started using different resolutions, and I set it in the game to be a certain resolution using VibranceGUi. I believe it is supposed to change my resolution back to 1920x1080 after closing the game? But it doesn't. It just stays at the custom resolution that I set it to in the VibranceGUI app. Any help would be appreciated. Thanks!

**Comment by caspertheghost1337** [comment]
Nope, I do not have a multi-monitor setup. I just tested auto switching resolutions in Spotify and it worked. It changed it to the specified resolution, and after tabbing out, it changed it back.

**Comment by caspertheghost1337** [comment]
I just found out what was wrong. I noticed a pattern in the resolution not changing. Every time the game's Digital Vibrance was at 100% the resolution wouldn't change back but for some reason now, it won't even change to the resolution. I changed the Digital Vibrance to 99% and the resolution changes both ways now when tabbing out.

**Comment by caspertheghost1337** [comment]
Accidentally closed it

**Comment by juv** [comment]
Are you using identical windows vibrance and in-game vibrance value?


caspertheghost1337 <notifications@github.com> schrieb am Sa. 29. Dez. 2018
um 00:36:

**Comment by caspertheghost1337** [comment]
Yes I am. Is that the problem?

**Comment by juv** [comment]
Why'd you do it in the first place and yes that might be the problem, you
gotta try it out though. Set windows to something lower than 100%, e.g. 99%
(you will barely see a difference anyways) and try it out please

caspertheghost1337 <notifications@github.com> schrieb am Sa. 29. Dez. 2018
um 00:46:

**Comment by caspertheghost1337** [comment]
I don't know, I just like Windows with 100% and I tried your suggestion, and it works with Fortnite, but CS:GO is just now launching and staying in the background.

**Comment by caspertheghost1337** [comment]
Found the solution for CS:GO. I had to add "-w 1280 -h 960 -windowed -noborder" to my launch options.
