### ISSUE TITLE
vibrancegui affecting computer

### ISSUE THREAD

**Issue by eejaehee** [juv/vibranceGUI#78]
i have a brand new computer that is currently going through some issues ever since i downloaded vibrancegui. I started having really bad lag after I opened it and still persists even after I close it. The color wouldn't appear when the app was open, but it appears once it is closed along with severe lag spikes that affects everything else like discord, game, and etc. Now I have some delay on my computer and I can't seem to get rid of vibrance completely since I can't find it under the uninstall programs, and it's not in apps either. I ran a computer diagnostics and it is saying that my CPU usage is higher than normal and my samsung evo is running below expected performance despite it being a brand new computer (I just got it 2 weeks ago or so). Please help, it's driving me nuts and I am super annoyed that it's affecting my new computer.

**Comment by juv** [comment]
Sounds like something weird is going on with your GPU drivers. Notice that vibranceGUI is not doing anything on its own itself, it just instructs your GPU driver to add the color to every image that is being output to your monitor. How, and when, the color is added is up to the driver. VibranceGUI itself is actually a really resource friendly application, barely using any CPU usage itself. You should never see vibranceGUI taking up any high CPU resources.

Try uninstalling your GPU driver with [Display Driver Uninstaller](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html). People had issues with latest NVIDIA gpu drivers, so you might try out an older version. I'd try out the same for AMD gpus as well.

Some people also had issues with some Windows versions, which caused some lagging when certain applications (including vibranceGUI) were running. Not sure what to do in this case, probably updating Windows.

**Comment by juv** [comment]
@eejaehee has this been fixed by reinstalling drivers?
