### ISSUE TITLE
Errors when login through RDP

### ISSUE THREAD

**Issue by wurzelpanzer** [juv/vibranceGUI#80]
When connecting through RDP to my machine and vibranceGUI is in autostart it throws an error. See screenshot.
[Error System.OutOfMemoryException](https://i.imgur.com/n0OIhD5.png)

**Comment by juv** [comment]
This might be related to drivers not being properly initialized or the driver temporary disables features. The exception could be catched but I'm afraid the cause of this is out of vibranceGUIs control
