### ISSUE TITLE
Vibrance gui changes stretched to black bars when press windows key

### ISSUE THREAD

**Issue by numerox** [juv/vibranceGUI#82]
Hi i have a problem when i reinstalled windows,i set 1280x960 resolution in windows and change to 144hz and its stretched,Then i open vibrance gui and run cs go, everything is fine but when i press windows key and back to cs go the game is with black bars, not stretched. any fix?

**Comment by juv** [comment]
If you are not using the "Change ingame resolution" option for CSGO.exe in vibranceGUI, then vibranceGUI is not controlling the resolution settings of your pc. Please give some more detailed information on how to reproduce this. What are your CSGO.exe settings in vibranceGUI?

**Comment by juv** [comment]
@numerox any update?
