### ISSUE TITLE
Locking mouse to primary monitor while Game window active

### ISSUE THREAD

**Issue by Homiephobia** [juv/vibranceGUI#85]
Would you consider adding a feature which locks the cursor to primary screen while selected game is active. 
I have this problem where I flick too fast while shooting and my cursor ends up on the other monitor, this causes the game to minimize.
I know there are third party apps for doing just that but I'd much rather see the functionality in something I already use.

**Comment by juv** [comment]
This is out of the scope from vibranceGUI
