### ISSUE TITLE
Windows 10 Update 1909 breaks it

### ISSUE THREAD

**Issue by rickgoemans** [juv/vibranceGUI#86]
I've just recently updated my Windows 10 to version 1909 and now it no longer works in any game.

Anybody else having the same problem?

I've tried:
- bordless windowed mode and fullscreen mode in PUBG, CSGO, Call of Duty MW
- re-adding the games
- running as administrator
- fresh download
- reboot
- clean nvidia driver install

Any suggestions?

**Comment by juv** [comment]
Hi, can you try to use "display driver uninstaller" to get rid of your
nvidia driver entirely? There might be corrupted left overs in your
installation. Uninstalling and reinstalling afterwards won't fix this
issues. Nvidia has not managed to fix this problem in a couple of years ago
using that tool and reinstalling afterwards might actually help.

Rick Goemans <notifications@github.com> schrieb am Mi. 4. Dez. 2019 um
16:09:

**Comment by rickgoemans** [comment]
Hey @juv, I've already tried DDU, it didn't work. 

Last night I fully reinstalled my pc (format disk and fresh install from USB with a Windows 10 1909 image) and I tested it with just PUBG and it worked fine.

Seems like something went wrong during the Windows update process.

**Comment by rickgoemans** [comment]
Yeah I've tried it with a couple of games now and they all work perfectly so I can confirm this is hasty issue report because of a bad Windows update.
