### ISSUE TITLE
Failed to determine Graphic Graphic Adapter Type

### ISSUE THREAD

**Issue by fasih12** [juv/vibranceGUI#88]
![Screenshot (30)](https://user-images.githubusercontent.com/44138043/74866331-86236600-5374-11ea-8968-315e86e300f8.png)

**Comment by fasih12** [comment]
@juv

**Comment by juv** [comment]
This was happening to some other people when the installed AMD drivers were corrupt or not properly installed. Some library files for the AMD driver are missing in those cases, which will end up in the error you see. Have you followed the instructions in the error message?

**Comment by juv** [comment]
@fasih12 any update? Have you reinstalled AMD drivers to see if that was the problem or if you have disabled any AMD driver component while installation?

**Comment by fasih12** [comment]
> @fasih12 any update? Have you reinstalled AMD drivers to see if that was the problem or if you have disabled any AMD driver component while installation?

yes just update the windows and this problem will fix.
