### ISSUE TITLE
Allow Lower then 50% Windows Vibrance Level

### ISSUE THREAD

**Issue by kylemathias** [juv/vibranceGUI#89]
The monitor I have for my PC I also use for my Xbox. The monitor I use has a built digital vibrance setting that I have set at 75%. I can compensate this in windows with setting the vibrance to 25%. It would be useful for me if VibraneGUI allowed a "Windows Vibrance Level" of anything between 0% to 100%. This isn't really an issue, but more of a feature request.

Thank you for your time.

**Comment by juv** [comment]
Hi, unfortunately this is not possible as the Nvidia driver API limits the
values in a range from 50% to 100% - even though the Nvidia control panel
itself can go lower than 50%.

Kyle Mathias <notifications@github.com> schrieb am So. 15. März 2020 um
02:29:

**Comment by juv** [comment]
Closing this as unfixable until the NVIDIA driver API changes. Seeing that the API has not changed significantly in a few years now, this is unlikely to happen anytime soon, sorry
