### ISSUE TITLE
Vibrance in CSGO lower when not using vibranceGUI

### ISSUE THREAD

**Issue by Chillkroete42** [juv/vibranceGUI#90]
Hi Juv,

I realised that the GUI did not work anymore which seems to be a problem of CS:GO. I dont why but when I close vibranceGUI CS is almost black/white. When I start the GUI again, everything is fine (which means it is standard) but without GUI CS will be like almost black and white. What I already tried to fix it:

- closed vibranceGUI, deleted all registry entries, removed all files (including the appdata\vibrancegui folder) restart, reset settings in Nvdia Driver back to standard
- uninstalled the graphics driver with DDU, reinstalled it

Please find the applicationData.xml and vibranceGUI.ini attached. I really dont what to do next, any help appreciated.

Thanks in advance! 
Regards, David
[appdata.zip](https://github.com/juv/vibranceGUI/files/4378147/appdata.zip)

**Comment by juv** [comment]
Uhm that is weird. When you uninstall with DDU, no driver files should be
left over. Vibrancegui only interacts with the API of the driver at runtime
so there should be no interference at all and no permanent left overs. Have
you made the driver changes to the digital vibrance settings in your Nvidia
control panel manually (without vibrancegui running)? 50% is the default
value, 100% max. Cs is greyish for me as well without any vibrancy added,
but not really b/w.

Chillkroete42 <notifications@github.com> schrieb am Mi. 25. März 2020 um
00:31:

**Comment by Chillkroete42** [comment]
Okay, I think it was my fault. I tested it again and it seems that CS looks is the same when putting vibrance on 100% in GeForce Driver on Windows or when using vibranceGUI(on Windows 50% and CS on 100%). But I could swear that CS wasnt so greyish before, but maybe I was so used to the vibrance adjustments...
Nevertheless, thanks a lot for your support and sorry for wasting your time ;-)
