### ISSUE TITLE
Vibrancegui just stopped working.

### ISSUE THREAD

**Issue by kom420** [juv/vibranceGUI#91]
I was using vibrancegui just fine but then it stopped working not affecting the colors of the desktop nor in game and was wondering if you could help. Started searching for it but nothing has worked out yet.

**Comment by juv** [comment]
Did you change your gpu driver?

kom420 <notifications@github.com> schrieb am Mo. 13. Apr. 2020 um 18:52:

**Comment by kom420** [comment]
I did uninstall my drivers with DDU and reinstalled some fresh ones but that didnt help . My rig is old but doubt thats the case cause ive been using VibranceGUI for sometime now but it randomly stopped. Does a hell of a job on Riots new game Valorant btw!!

**Comment by juv** [comment]
Yes that should help. If it's not helping, you should explain your error in
more detail. When did it stop working, what did you change in your system
before it stopped working. DDU + reboot + install gpu driver + reboot
should help indeed, it's weird that you say it is not. Which gpu do you
have?

kom420 <notifications@github.com> schrieb am Mo. 13. Apr. 2020 um 19:10:

**Comment by kom420** [comment]
I didnt actually change anything its just stopped working i was using it just fine and then i opened it couple days ago and it didnt affect even i put it to 0 or 300 it was the same for desktop and in-games . I have an HD series 7700 . "DDU + reboot + install gpu driver + reboot" thats what i tried at first but didnt work and then googled my problem but didnt find anything about it so i came here to ask for help.

**Comment by juv** [comment]
I see. We had some reports that the latest amd drivers do not include the
necessary amd api files. People went back to some previous gpu driver
versions and made sure they did not install some kind of performance
version of the drivers. Unfortunately i never had an amd gpu so i hope we
can figure this out

kom420 <notifications@github.com> schrieb am Mo. 13. Apr. 2020 um 21:16:

**Comment by kom420** [comment]
Its just so weird to randomly stop working and even after the new drivers to keep doing the same thing . Well if it doesnt get fixed its alright its just a big rip cause that program is game changing.

**Comment by kom420** [comment]
Just a quick update i tried reinstalling the drivers , it did work but it didnt as well. The program now applies the vibrance only after i close it .

**Comment by juv** [comment]
Sounds like you have not properly set in-game and windows vibrance levels?
Windows level is typically left at default (100 for amd) and in game is set
for each application, but typically higher than 100 to even see a difference

kom420 <notifications@github.com> schrieb am Mo. 13. Apr. 2020 um 23:43:

**Comment by aidendeom** [comment]
Hi, I'm having similar issues with an Nvidia GPU. If I modify the "Windows Vibrance Level" slider, the changes are only applied after I close VibranceGUI or if I double click a program settings button.

Additionally, the program specific settings are no longer applied when that program gains focus.

**Comment by juv** [comment]
@aidendeom I have just tried it with 2.3.1.1 on NVIDIA.
It's working as expected for me:
1) Windows vibrance level is at 50% (default)
2) I change the Windows vibrance level slider to 75%, color is not affected until another process gets focus
3) When I tab into another process, the 75% is now applied. The color is also changed if I double click on an application icon in vibranceGUI (which opens the specific program vibrance settings)
4) when I tab into a program that is added to vibranceGUI, for example Google Chrome, I see that the vibrance level gets applied to the value that is set for Google Chrome.

Note that you can best "verify" this when you set Windows vibrance level to 100% and another application such as Google Chrome to 50%. In my opinion, the switch from 100% -> 50% is more visible than the other way around.

Is there anything I am missing?

**Comment by aidendeom** [comment]
I tried what you said with Chrome, and it is indeed working as expected. I will need to try again with a fullscreen application to see if I can better describe what is not working.

**Comment by juv** [comment]
@kom420 @aidendeom any update?
