### ISSUE TITLE
2 GPUS problem

### ISSUE THREAD

**Issue by mtoloto** [juv/vibranceGUI#93]
Hello, 

I have a GTX 770 and a RADEON 7870 pluged on my pc.

The 770 I use to play games and as a main gpu, the 7870 I use as a dedicated encoder to stream... but I cant open vibranceGUI because it gives me this error:

"Both NVIDIA and AMD graphic drivers have been found on your system. This can happen when you recently switched your graphic card and did not uninstall the old drivers. Make sure to uninstall unused graphic drivers to keep your system safe and stable. Use the program "Display Driver Uninstaller" to uninstall your old drivers!"

any way to force it to nvidia only?

**Comment by juv** [comment]
Maybe you can try out this for the time being: https://github.com/juv/vibranceGUI/issues/67#issuecomment-452063846

**Comment by juv** [comment]
@mtoloto have you tried the builds in that link above?
