### ISSUE TITLE
Connect laptop to extended monitor

### ISSUE THREAD

**Issue by madavemger** [juv/vibranceGUI#94]
When u connect ur laptop to extended monitor u cant increase saturation and vibrance in extended monitor this option i tell u will fix ur problem 

To answer your question:
1. Click on Start.

2. Search for 'regedit.exe' and run the application.

3. Click on 'Edit' -> 'Find'.

4. Type in XVYCCFeatureEnable (Note: This is key sensitive) and hit Enter.

The default location for this key should be: [HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0000\]

5. Right-click on the 'XVYCCFreatureEnable' and select 'Modify'.

6. Replace the default hexadecimal value 1 with 0

7. Click 'Ok'.

8. Restart the computer.

**Comment by juv** [comment]
Hi, thanks for the report! I'm sure people will find this issue via Google. 
I'll go ahead and close this as it is not really an "issue".
