### ISSUE TITLE
System.OutofMemoryException: Exception of type

### ISSUE THREAD

**Issue by connect192168** [juv/vibranceGUI#96]
I'm running a nvidia GeForce 940MX and Intel integrated graphics 630.
Priority is globally set to the nvidia card via the nvidia control center.

I downloaded the application 10 minutes ago.
I run it and this error shows up after about a minute:
![image](https://user-images.githubusercontent.com/38689351/87681487-9d754c80-c776-11ea-8ae4-d45798ce97d3.png)

**Comment by juv** [comment]
Yes, I could definitely catch that exception in a newer version, however you shouldn't download + run an application when the website says that your device (nvidia laptop) is not supported :)
