### ISSUE TITLE
Error when launching vibrance with csgo "systemoutofmemory"

### ISSUE THREAD

**Issue by Tarkinn** [juv/vibranceGUI#97]
So i just installed vibrance cause nvidia is not supported anymore due to the last vac update regarding .dll.
But when i launch it it gives me this error with the total inability to click on any button of VibranceGui window except for the resolution. 
For translation ''à'' means ''to''
And it is written "an exception of  type 'Systemoutofmemory' has been found/raised.
![ViBug](https://user-images.githubusercontent.com/47140244/91469468-b738a200-e893-11ea-8b48-f40ca3226b22.PNG)

I'll try to get back here for updates but i'm moving out tomorrow so maybe i'll not show up in a while.
Just wanted to share this error with you.

Thx.

**Comment by juv** [comment]
This happens when you either have 
1) a nvidia laptop, which is not supported as stated on the website
2) a corrupted nvidia gpu driver installation. if this is the case, uninstall nvidia driver and install it again.

**Comment by Tarkinn** [comment]
Oh i'm sorry i wasted your time. I indeed have a Nvidia Laptop. I did not
read what was in the website, only the steam page and readme.txt my bad.
Have a good day

**Comment by juv** [comment]
Hi, can you explain how you set the color effects? Please take screenshot
of it. I can probably clear up your confusion after seeing the screenshots.

Thanks

Tarkinn <notifications@github.com> schrieb am Mi. 13. Jan. 2021 um 18:05:

**Comment by Tarkinn** [comment]
hey, i didn't touch the color options at all, i just used vibrance as a normal user would do. I only added those nvidia control panel as a note of things i noticed.
The only change i made was to connect my laptop to a second screen.

**Comment by juv** [comment]
@Tarkinn so you say with your second monitor attached, you have the Digital Vibrance option in your NVIDIA Control Panel? We're not talking about contrast/brightness/gamma here.

![image](https://user-images.githubusercontent.com/8269353/104770745-5aba1e80-5771-11eb-9b01-5ca04f04be97.png)

**Comment by Tarkinn** [comment]
Absolutely I even changed it to 100% yesterday so i am sure it works. here's a video to show you : https://youtu.be/NL-n5qjvgbw 
https://youtu.be/y1FdOT1QV2c , as you see it's not a matter of nvidia laptop graphic cards not supporting vibrance (like you say on your site) but more a matter of laptop screen not offering color/light options though i don't know why. I can only guess monitors have some kind of chip allowing to control r/v/b light/contrast etc that laptop don't have so laptop just display raw image while monitor are able to change it following your demands.
I tested it on another screen and it works too. Now you just have to test serveral laptops and i think you will be good to add this option on your website so that people know it exist.

**Comment by juv** [comment]
And you can use vibranceGUI when you have your second monitor plugged in? Without error message and everything is working?

**Comment by Tarkinn** [comment]
yes, at least on the screen i tested.

**Comment by Tarkinn** [comment]
I randomly found that (look the right part of the screenshot) as you see my laptop screen's color settings are monitored by intel and my second screen's colors are monitored by my gpu so that's kinda funny.
![image](https://user-images.githubusercontent.com/47140244/106599150-f5c83c00-6558-11eb-9ed5-1d55c98bfebf.png)
